'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const {mkdtemp,rm}=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
test('digital lending, exact anchors, resource types, rankings and persistence',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'bookloop-'));let child;
 const start=()=>new Promise((resolve,reject)=>{child=spawn(process.execPath,['app.js'],{env:{...process.env,LIBRARY_DB:path.join(dir,'test.db'),PORT:'0',BRAVE_SEARCH_API_KEY:''}});let output='';const timer=setTimeout(()=>reject(Error('startup timeout')),10000);child.stdout.on('data',chunk=>{output+=chunk;const m=output.match(/Listening on port (\d+)/);if(m){clearTimeout(timer);resolve('http://127.0.0.1:'+m[1]);}});child.on('exit',code=>{clearTimeout(timer);if(code)reject(Error('server exit '+code));});});
 const stop=()=>new Promise(resolve=>{child.once('exit',resolve);child.kill();});
 try {
 let base=await start(),cookie='';const login=async(mode='login')=>{const r=await fetch(base+'/api/account/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'reader_one',password:'a-test-password'})});assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0];};await login('register');const request=(url,method='GET',body)=>fetch(base+'/api/digital'+url,{method,headers:{Cookie:cookie,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
 const books=await (await request('/resources')).json();assert.equal(books.length,6);const book=books[0];
 require('node:child_process').execFileSync(process.execPath,['scripts/set-admin.js','reader_one'],{env:{...process.env,LIBRARY_DB:path.join(dir,'test.db')}});
 const configured=await request('/resources/'+book.id,'PUT',{...book,tags:book.tags.join(','),content:book.paragraphs.join('\n\n'),lending:'limited',seats:1,loanDays:14});assert.equal(configured.status,200);Object.assign(book,await configured.json());
 const body={version:book.version,paragraph:0,start:0,end:10,quote:book.paragraphs[0].slice(0,10),note:'需要结合上下文理解'};
 assert.equal((await request('/annotations/'+book.id,'POST',body)).status,409);
 const attempts=await Promise.all([request('/loans/'+book.id,'POST'),request('/loans/'+book.id,'POST')]);
 assert.deepEqual(attempts.map(r=>r.status).sort(),[200,409]);
 assert.match((await (await request('/loans/'+book.id,'POST')).json()).error,/已被借走/);
 await stop();base=await start();await login();
 assert.equal((await (await request('/resources')).json()).find(b=>b.id===book.id).borrowed,true);
 assert.equal((await (await request('/history')).json()).length,1);
 assert.equal((await request('/annotations/'+book.id,'POST',{...body,quote:'wrong'})).status,400);
 assert.equal((await request('/annotations/'+book.id,'POST',{...body,version:'wrong'})).status,400);
 assert.equal((await request('/annotations/'+book.id,'POST',body)).status,200);
 await request('/loans/'+book.id,'DELETE');
 assert.equal((await (await request('/resources')).json()).find(b=>b.id===book.id).borrowed,false);
 assert.equal((await request('/loans/'+book.id,'POST')).status,200);
 await request('/loans/'+book.id,'DELETE');
 assert.equal((await (await request('/annotations/'+book.id)).json()).length,1);
 assert.equal((await request('/annotations/'+book.id,'POST',body)).status,409);
 assert.equal((await request('/resources','POST',{title:'bad',kind:'link',url:'javascript:alert(1)'})).status,400);
 const created=await (await request('/resources','POST',{title:'参考文章',kind:'article',url:'https://example.org/article',tags:'NATURE, nature, KNOWLEDGE',content:'First paragraph.\n\nSecond paragraph.'})).json();
 assert.deepEqual(created.tags,['NATURE','KNOWLEDGE']);assert.equal(created.paragraphs.length,2);
 assert.equal((await request('/loans/'+created.id,'POST')).status,200);
 assert.equal((await request('/loans/'+created.id,'POST')).status,409);
 assert.equal((await (await request('/resources')).json()).find(b=>b.id===created.id).borrowedByMe,true);
 assert.ok((await (await request('/history')).json()).some(h=>h.resource_id===created.id));
 assert.equal((await request('/loans/'+created.id,'DELETE')).status,200);
 assert.equal((await (await request('/resources')).json()).find(b=>b.id===created.id).borrowedByMe,false);
 const linked=await (await request('/resources','POST',{title:'Reference link',kind:'link',url:'https://example.org/reference',tags:'REFERENCE'})).json();
 assert.equal((await request('/loans/'+linked.id,'POST')).status,200);
 assert.equal((await request('/loans/'+linked.id,'DELETE')).status,200);
 const note={version:created.version,paragraph:1,start:0,end:6,quote:'Second',note:'文章无需借阅也可批注'};
 assert.equal((await request('/annotations/'+created.id,'POST',note)).status,200);
 await request('/events/'+created.id,'POST',{kind:'view'});
 const ranks=await (await request('/rankings')).json();assert.equal(ranks.view[0].resource_id,created.id);assert.equal(ranks.loan[0].count,2);
 await stop();base=await start();await login();
 assert.equal((await (await request('/resources')).json()).length,8);
 const notes=await (await request('/annotations/'+created.id)).json();assert.equal(notes[0].quote,'Second');
 await request('/annotation/'+notes[0].id,'DELETE');assert.equal((await (await request('/annotations/'+created.id)).json()).length,0);
 }finally{if(child&&child.exitCode===null)await stop();await rm(dir,{recursive:true,force:true});}
});
