'use strict';
const {randomUUID}=require('crypto');
const accounts=require('./accounts');
const {sql,fail,safeURL,text,anchor,resource,notify}=require('./digital-core');
module.exports=register=>{
 let ready;
 async function setup(){
  await sql(`CREATE TABLE IF NOT EXISTS digital_discussions(id TEXT PRIMARY KEY,resource_id TEXT NOT NULL,user_id TEXT NOT NULL,version TEXT NOT NULL,paragraph INTEGER NOT NULL,start INTEGER NOT NULL,end INTEGER NOT NULL,quote TEXT NOT NULL,kind TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',hidden INTEGER NOT NULL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
  await sql(`CREATE TABLE IF NOT EXISTS digital_replies(id TEXT PRIMARY KEY,discussion_id TEXT NOT NULL,user_id TEXT NOT NULL,body TEXT NOT NULL,source_url TEXT NOT NULL,source_location TEXT NOT NULL,hidden INTEGER NOT NULL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
  await sql('CREATE TABLE IF NOT EXISTS digital_helpful(reply_id TEXT NOT NULL,user_id TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(reply_id,user_id))');
  await sql('CREATE TABLE IF NOT EXISTS digital_reports(id INTEGER PRIMARY KEY,user_id TEXT NOT NULL,target_type TEXT NOT NULL,target_id TEXT NOT NULL,reason TEXT NOT NULL,resolved INTEGER NOT NULL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,target_type,target_id))');
  await sql('CREATE TABLE IF NOT EXISTS digital_practice(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,resource_id TEXT NOT NULL,before_text TEXT NOT NULL,after_text TEXT NOT NULL,action_text TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)');
 }
 const route=(p,m,fn)=>register(p,m,async req=>{await(ready ||= setup());return fn(req);});
 async function thread(id){const [d]=await sql('SELECT * FROM digital_discussions WHERE id=? AND hidden=0',[id]);if(!d)fail('讨论不存在或已撤回',404);await resource(d.resource_id);return d;}
 route('/discussions/:resource','get',async req=>{await resource(req.params.resource);const rows=await sql('SELECT d.*,u.username FROM digital_discussions d JOIN digital_users u ON u.id=d.user_id WHERE resource_id=? AND hidden=0 ORDER BY d.created_at DESC,d.id',[req.params.resource]);for(const d of rows){d.mine=d.user_id===req.session.user?.id;delete d.user_id;d.replies=await sql(`SELECT r.id,r.body,r.source_url,r.source_location,r.created_at,u.username,r.user_id,(SELECT COUNT(*) FROM digital_helpful h WHERE h.reply_id=r.id) helpful FROM digital_replies r JOIN digital_users u ON u.id=r.user_id WHERE discussion_id=? AND r.hidden=0 ORDER BY r.created_at,r.id`,[d.id]);for(const r of d.replies){r.mine=r.user_id===req.session.user?.id;delete r.user_id;r.helped=!!(await sql('SELECT 1 FROM digital_helpful WHERE reply_id=? AND user_id=?',[r.id,req.session.user?.id||''])).length;}}return rows;});
 route('/discussions/:resource','post',async req=>{const user=accounts.requireUser(req),r=await resource(req.params.resource),b=req.body;anchor(r,b);if(!['question','explanation','translation','reflection'].includes(b.kind))fail('请选择讨论类型');if(b.publish!==true)fail('请确认公开发布');const id=randomUUID();await sql('INSERT INTO digital_discussions(id,resource_id,user_id,version,paragraph,start,end,quote,kind,body) VALUES(?,?,?,?,?,?,?,?,?,?)',[id,r.id,user,r.version,b.paragraph,b.start,b.end,b.quote,b.kind,text(b.body,'讨论内容',3000)]);return {ok:true,id};});
 route('/discussion/:id/replies','post',async req=>{const user=accounts.requireUser(req),d=await thread(req.params.id),b=req.body,id=randomUUID();const body=text(b.body,'回复',3000),source=text(b.source_url||'','来源',2000,false),location=text(b.source_location||'','依据位置',300,false);if(!source&&!location)fail('请补充来源链接或原文段落依据');await sql('INSERT INTO digital_replies(id,discussion_id,user_id,body,source_url,source_location) VALUES(?,?,?,?,?,?)',[id,d.id,user,body,source?safeURL(source):'',location]);if(user!==d.user_id)await notify(d.user_id,'reply','你的段落讨论收到新回复。',d.resource_id+'#'+d.id);return {ok:true,id};});
 route('/discussion/:id/status','post',async req=>{const user=accounts.requireUser(req),d=await thread(req.params.id);if(d.user_id!==user)fail('仅发起者可以更新讨论状态',403);if(!['open','resolved','disputed'].includes(req.body.status))fail('无效讨论状态');await sql('UPDATE digital_discussions SET status=? WHERE id=?',[req.body.status,d.id]);return {ok:true};});
 route('/reply/:id/helpful','post',async req=>{const user=accounts.requireUser(req),[r]=await sql('SELECT * FROM digital_replies WHERE id=? AND hidden=0',[req.params.id]);if(!r)fail('回复不存在',404);await thread(r.discussion_id);if(r.user_id===user)fail('不能标记自己的回复');if(req.body.helped===false)await sql('DELETE FROM digital_helpful WHERE reply_id=? AND user_id=?',[r.id,user]);else await sql('INSERT OR IGNORE INTO digital_helpful(reply_id,user_id) VALUES(?,?)',[r.id,user]);return {ok:true};});
 route('/community/:type/:id','delete',async req=>{const user=accounts.requireUser(req),table=req.params.type==='discussion'?'digital_discussions':req.params.type==='reply'?'digital_replies':null;if(!table)fail('类型错误');const rows=await sql(`UPDATE ${table} SET hidden=1 WHERE id=? AND user_id=? RETURNING id`,[req.params.id,user]);if(!rows.length)fail('只能撤回自己的内容',403);return {ok:true};});
 route('/reports','post',async req=>{const user=accounts.requireUser(req),b=req.body;if(!['discussion','reply'].includes(b.type))fail('类型错误');if(b.type==='discussion')await thread(b.id);else {const [r]=await sql('SELECT discussion_id FROM digital_replies WHERE id=? AND hidden=0',[b.id]);if(!r)fail('回复不存在',404);await thread(r.discussion_id);}await sql('INSERT OR IGNORE INTO digital_reports(user_id,target_type,target_id,reason) VALUES(?,?,?,?)',[user,b.type,b.id,text(b.reason,'举报原因',1000)]);return {ok:true};});
 route('/admin/reports','get',async req=>{await accounts.requireAdmin(req);const reports=await sql('SELECT * FROM digital_reports ORDER BY resolved,id DESC');for(const r of reports){const table=r.target_type==='discussion'?'digital_discussions':'digital_replies';r.content=(await sql(`SELECT body FROM ${table} WHERE id=?`,[r.target_id]))[0]?.body||'内容已不存在';}return reports;});
 route('/admin/reports/:id','post',async req=>{await accounts.requireAdmin(req);const [r]=await sql('SELECT * FROM digital_reports WHERE id=?',[req.params.id]);if(!r)fail('举报不存在',404);if(!['hide','dismiss'].includes(req.body.action))fail('无效处理');if(req.body.action==='hide')await sql(`UPDATE ${r.target_type==='discussion'?'digital_discussions':'digital_replies'} SET hidden=1 WHERE id=?`,[r.target_id]);await sql('UPDATE digital_reports SET resolved=1 WHERE id=?',[r.id]);return {ok:true};});
 route('/community-feed','get',async()=>sql(`SELECT d.id,d.resource_id,d.quote,d.body,d.status,u.username,(SELECT COUNT(*) FROM digital_replies r WHERE r.discussion_id=d.id AND r.hidden=0) replies FROM digital_discussions d JOIN digital_users u ON u.id=d.user_id JOIN digital_resources b ON b.id=d.resource_id WHERE d.hidden=0 AND COALESCE(json_extract(b.data,'$.archived'),0)=0 ORDER BY CASE WHEN d.status='open' THEN 0 ELSE 1 END,d.created_at DESC LIMIT 20`));
 route('/practice/:id','post',async req=>{const user=accounts.requireUser(req);await resource(req.params.id);const b=req.body;await sql('INSERT INTO digital_practice(id,user_id,resource_id,before_text,after_text,action_text) VALUES(?,?,?,?,?,?)',[randomUUID(),user,req.params.id,text(b.before,'最初理解',2000),text(b.after,'修正后的理解',2000),text(b.action,'下一步行动',2000)]);return {ok:true};});
 route('/practice','get',req=>sql('SELECT * FROM digital_practice WHERE user_id=? ORDER BY created_at DESC',[accounts.requireUser(req)]));
 route('/admin/metrics','get',async req=>{await accounts.requireAdmin(req);return {discussions:(await sql('SELECT COUNT(*) n FROM digital_discussions WHERE hidden=0'))[0].n,answered:(await sql('SELECT COUNT(*) n FROM digital_discussions d WHERE hidden=0 AND EXISTS(SELECT 1 FROM digital_replies r WHERE r.discussion_id=d.id AND r.hidden=0)'))[0].n,resolved:(await sql("SELECT COUNT(*) n FROM digital_discussions WHERE hidden=0 AND status='resolved'"))[0].n,helpful:(await sql('SELECT COUNT(*) n FROM digital_helpful h JOIN digital_replies r ON r.id=h.reply_id JOIN digital_discussions d ON d.id=r.discussion_id WHERE r.hidden=0 AND d.hidden=0'))[0].n,practice:(await sql('SELECT COUNT(*) n FROM digital_practice'))[0].n};});
};
